config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root 'lists#index'

  devise_scope :user do
    get '/users/sign_out' => 'sessions#destroy'
  end

  resources :users, only: [:show, :edit, :update]
  resources :lists
  resources :tasks
  get '/new_user', to: 'unidentified_users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  def active_tasks
    active_tasks = []
    self.tasks.each do |task|
      active_tasks.push(task) if task.is_active == true
    end
    active_tasks
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :list

  belongs_to :main_task, class_name: "Task", foreign_key: "main_task_id", optional: true
  has_many :subtasks, class_name: "Task", foreign_key: "main_task_id", dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :turbo_frame_request_variant

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def turbo_frame_request_variant
    request.variant = :turbo_frame if turbo_frame_request?
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    if user_signed_in?
      @lists = List.where(user_id: current_user.id)
    else
      redirect_to new_user_path
    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(name: params[:name], user_id: params[:user_id], archived: false)
    @list.save
  end

  def show
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      redirect_to "/"
    else
      render :show, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.name = params[:name]
    if @list.save
      redirect_to @list
    else
      render :edit, status: :unprocessable_entity
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
    @list = List.find(params[:list_id])
  end

  def create
    @task = Task.new(title: params[:name],
                     body: params[:body],
                     list_id: params[:list_id],
                     user_id: params[:user_id],
                     is_active: true)
    @task.save
    @list = List.find(params[:list_id])
  end
end

app/controllers/unidentified_users_controller.rb
class UnidentifiedUsersController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/unidentified_users_helper.rb
module UnidentifiedUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="antialiased bg-gradient-to-r from-pink-300 via-purple-300 to-indigo-400">
    <header>
      <nav class="flex flex-wrap items-center justify-between w-full py-4 md:py-0 px-4 text-lg text-gray-700 bg-white">
        <a href="/">ToDoApp</a>
        <div class="cursor-pointer md:hidden block" id="menu-button">Menu</div>
        <div class="hidden w-full md:flex md:items-center md:w-auto " id="menu">
          <ul class="text-base text-gray-700 pt-4 md:flex md:justify-between md:pt-0">
            <% if user_signed_in? %>
              <li>
                <!--%= button_to( "Profile", user_path, method: :get, class: "md:p-4 py-2 block hover:text-purple-400" ) %-->
                <a class="md:p-4 py-2 block hover:text-purple-400" href="/users/<%= current_user.id %>">Profile</a>
              </li>
              <li>
                <%= button_to( "Sign Out", destroy_user_session_path, method: :delete, class: "md:p-4 py-2 block hover:text-purple-400" ) %>
              </li>
            <% else %>
              <li>
                <%= button_to( "Sign In", new_user_session_path, method: :get, class: "md:p-4 py-2 block hover:text-purple-400" ) %>
                <!-- a class="md:p-4 py-2 block hover:text-purple-400 text-purple-500" href="<%= new_user_session_path %>">Sign In</a -->
              </li>
              <li>
                <%= button_to( "Sign Up", new_user_registration_path, method: :get, class: "md:p-4 py-2 block hover:text-purple-400" ) %>
                <!-- a class="md:p-4 py-2 block hover:text-purple-400 text-purple-500" href="<%= new_user_registration_path %>">Sign Up</a -->
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <div class="<%= "hidden" if notice.nil? || alert.nil? %> flex justify-center items-center bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <span class="block sm:inline">
        <%= notice %>
        <%= alert %>
      </span>
    </div>
    <main>
      <div class="min-h-full flex items-center justify-center py-6 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/lists/_lists.html.erb
<% unless current_user.lists.length.zero? %>
  <div class="mt-5">
    <% current_user.lists.each do |list| %>
      <div class="flex justify-center">
        <%= link_to list.name, "/lists/#{list.id}", class: "relative w-10/12 flex justify-center my-1 py-2 px-4 border border-transparent rounded-md bg-gray-100 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", data: { turbo: false } %><br>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="mt-5 text-center">You have not created any lists yet.</p>
<% end %>

app/views/lists/_new_list.html.erb
<%= form_with(url: "/lists", method: "POST", data: { turbo_frame: "lists" }) do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.label :name, class: "sr-only" %>
  <%= form.text_field :name, class: "appearance-none rounded-lg relative block w-full px-3 py-2 mb-6 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "List name" %>
  <%= form.submit "Create list", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<% end %>

app/views/lists/create.html+turbo_frame.erb
<%= turbo_frame_tag "lists" do %>
  <%= render "lists" %>
<% end %>

app/views/lists/edit.html.erb
<h1 class="mt-6 text-center text-3xl text-gray-900">Edit <%= @list.name %> name</h1>

<%= form_with(url: "/lists/#{@list.id}", method: :patch, data: { turbo: false } ) do |form| %>
  <%= form.label :name, class: "sr-only" %>
  <%= form.text_field :name, autofocus: true, class: "appearance-none rounded-lg relative block w-full px-3 py-2 mb-6 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "#{@list.name}" %> 

  <%= form.submit "Edit list name", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<% end %>

app/views/lists/index.html.erb
<h1 class="mt-6 text-center text-3xl text-gray-900">Your lists</h1>

<%= turbo_frame_tag "lists" do %>
  <%= render "lists" %>
<% end %>

<div class="mt-10">
  <%= turbo_frame_tag "new-list" do %>
    <%= form_with(url: new_list_path, method: "GET", data: { turbo_frame: "new-list" }) do |form| %>
      <%= form.submit "Create new list", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html+turbo_frame.erb
<%= turbo_frame_tag "new-list" do %>
  <%= render "new_list" %>
<% end %>

app/views/lists/new.html.erb
<%= turbo_frame_tag "new-list" do %>
  <%= render "new_list" %>
<% end %>

app/views/lists/show.html.erb
<h1 class="mt-6 text-center text-3xl text-gray-900"><%= @list.name %></h1>

<div class="tasks">
  <%= turbo_frame_tag "tasks" do %>
    <%= render "/tasks/tasks", tasks: @list.tasks %>
  <% end %>
</div>

<div class="mt-10">
  <%= turbo_frame_tag "new-task" do %>
    <%= form_with(url: new_task_path, method: "GET", data: { turbo_frame: "new-task" }) do |form| %>
      <%= form.hidden_field :list_id, value: @list.id %>
      <%= form.submit "New task", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    <% end %>
  <% end %>
</div>

<div class="">
  <%= button_to "Edit list name", "/lists/#{@list.id}/edit", method: :get, class: "w-full flex justify-center my-2 py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  <%= button_to "Delete list", "/lists/#{@list.id}", method: :delete, class: "w-full flex my-2 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
</div>

app/views/tasks/_new_task.html.erb
<%= form_with(url: "/tasks", method: "POST", data: { turbo_frame: "tasks", controller: "form-reset", action: "turbo:submit-end->form-reset#reset" }) do |form| %>
  <%= form.hidden_field :list_id, value: @list.id %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.label :name, class: "sr-only" %>
  <%= form.text_field :name, class: "appearance-none rounded-lg relative block w-full px-3 py-2 mb-6 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "Task name" %>
  <%= form.label :body, class: "sr-only" %>
  <%= form.text_field :body, class: "appearance-none rounded-lg relative block w-full px-3 py-2 mb-6 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "Description" %>
  <%= form.submit "Create task", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<% end %>

app/views/tasks/_tasks.html.erb
<% tasks.each do |task| %>
  <div class="">
    <%= task.title %>
    <% unless task.body.nil? %>
      <p class="ml-3"> 
        <%= task.body[..10] %><%= '...' if task.body.length > 10  %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/tasks/create.html.erb
<%= turbo_frame_tag "tasks" do %>
  <%= render "tasks", tasks: @list.tasks %>
<% end %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "new-task" do %>
  <%= render "new_task" %>
<% end %>

app/views/unidentified_users/index.html.erb
<h2 class="text-center">Please <%= link_to "sign up", new_user_registration_path, class: "underline underline-offset-4 hover:text-gray-500" %> or <%= link_to "sign in", new_user_session_path, class: "underline underline-offset-4 hover:text-gray-500" %></h2>

app/views/users/edit.html.erb
<h1 class="mt-6 text-center text-3xl text-gray-900">Nickname</h1>

<%= form_for(@user, url: "/users/#{current_user.id}", data: { turbo: false }, class: "flex items-center") do |f| %>
  <div>
    <%= f.label :nickname, class: "sr-only" %><br/>
    <%= f.text_field :nickname, autofocus: true, class: "appearance-none rounded-lg relative block w-full px-3 py-2 mb-6 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm", placeholder: "#{current_user.nickname}" %>
  </div>

  <div>
    <%= f.submit "Edit nickname", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1 class="mt-6 text-center text-3xl text-gray-900">Hi, <%= current_user.nickname %></h1>

<a class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" href="/users/<%= current_user.id %>/edit">Edit Nickname</a>